#!/usr/bin/env sh


EMAIL=xxxxxxxxxxxxxxxxx

echo "
This message was generated by the nut-monitor daemon running on:

	hostname:	$(hostname)
	domain:		$(dnsdomainname)

The following error was detected by the nut-monitor daemon:

	UPS: ${UPSNAME}
	Alert type: ${NOTIFYTYPE}

STATUS
------
$(upsc ${UPSNAME})
" | mail --subject "NUT error (${NOTIFYTYPE}) detected on host: $(hostname)" ${EMAIL}
